### ISSUE TITLE
Socket interface for BBB with local host #1

### ISSUE THREAD

**Issue by Kushagra42** [cu-ecen-5013/final-project-Kushagra42#1]
In progress

**Comment by Kushagra42** [comment]
DoD: Connection established between server and client on local host. Client sends the data to server on every connection. Server appends the data in /var/tmp/aesdsocketdata.txt

**Comment by Kushagra42** [comment]
Status update: Connection established on local host. Successful transmission of a string/data from client to server

**Comment by Kushagra42** [comment]
link to the closed issue: https://github.com/cu-ecen-5013/final-project-Kushagra42.git

**Comment by steveantony5** [comment]
@Kushagra42  Please edit the first comment and move the dod there
Refer: https://docs.google.com/document/d/1nHiCKOrHSQBuZVDpSXKqPFwV5W3lHyvE4heCGnz7ghw/edit referencing step 3.f
