### ISSUE TITLE
Sensor interface, UART for Arduino and SPI driver for Beaglebone

### ISSUE THREAD

**Issue by Kushagra42** [cu-ecen-5013/final-project-Kushagra42#2]
Sensor interface on Arduino. Send sensor data to Beaglebone via UART. Write the SPI driver code for Beaglebone.

DoD: Able to read senor value on arduino and beaglebone. Able to send sensor readings from arduino to beaglebone.

**Comment by Kushagra42** [comment]
Status: ADC sensor interface and  UART completed on Arduino

**Comment by Kushagra42** [comment]
Blocker: Arduino to BBB testing can only be done Once UART driver is ready for BBB

**Comment by steveantony5** [comment]
@Kushagra42  The first comment should explain what is this task for
and dod should explain how will you verify it.

Not everthing should be under dod

**Comment by Kushagra42** [comment]
Blocker closed: UART setup us successful. Communication between Arduino and UART established correctly.
UART patch link: https://github.com/cu-ecen-5013/final-project-Vaidehisalway/blob/master/base_external/patches/linux/uart.patch

**Comment by Kushagra42** [comment]
Status Update: 1. Was able to read correct sensor data on Arduino and sent to beaglebone via UART.
https://github.com/cu-ecen-5013/final-project-Kushagra42/blob/master/Arduino%20Application%20code/Arduino_uart.ino (43c6dd57af5f28a413c4a56afad9b0a0c261b770 )
2. Wrote the SPI code to read the raw sensor data on Beaglebone.
https://github.com/cu-ecen-5013/final-project-Kushagra42/tree/master/SPI_TEMP(43c6dd57af5f28a413c4a56afad9b0a0c261b770 )
3. Added a partially working patch for SPI to base_externel.
https://github.com/cu-ecen-5013/final-project-Vaidehisalway/blob/master/base_external/patches/linux/spi1_s0.patch (e811ad776e9ca3cb5ba776bf190f7f15d397cdeb)
