### ISSUE TITLE
Sprint 3

### ISSUE THREAD

**Issue by Kushagra42** [cu-ecen-5013/final-project-Kushagra42#3]
ToDo: Write the completely working  SPI Patch for beaglebone and read the  SPI temperature sensor data. Send sensor readings received on Beaglebone to PC using socket.

DoD: Able to display data from sensors on the host machine.

**Comment by Kushagra42** [comment]
Blocker: Patch is not able to load the SPI module to /dev on beaglebone
https://github.com/cu-ecen-5013/final-project-Kushagra42/blob/master/SPI_TEMP/spi1_s0.patch

**Comment by Vaidehisalway** [comment]
Status Update:
1. Improved on socket and client code to allow easy functioning and integration with the main script.
Client-https://github.com/cu-ecen-5013/final-project-Kushagra42/blob/master/Socket_Client/Client.c(aaeaa79fb8f3a6fa06acfcd6d6da154248f113e9)
Server-https://github.com/cu-ecen-5013/final-project-Kushagra42/blob/master/Socket_Server/Server.c(cdf28be631b43de5fb94e110000c8c263325818e)

**Comment by Vaidehisalway** [comment]
Status Update: SPI Blocker: Since I was not able to load the SPI module successfully I have decided to move to an I2C based sensor after consulting with professor. Here I am attaching the link for the work that I had done working on SPI (Although I will not be using this content).
SPI patch:https://github.com/cu-ecen-5013/final-project-Kushagra42/blob/master/SPI_TEMP/spi1_s0.patch(9b815f2d1683f0d97905233849c4b5f8a0683c0f)
SPI application code: https://github.com/cu-ecen-5013/final-project-Kushagra42/blob/master/SPI_TEMP/spi_test.c(43c6dd57af5f28a413c4a56afad9b0a0c261b770)

**Comment by Vaidehisalway** [comment]
Status: Closing this issue as I am moving to I2C based sensor for which I have created a new issue.

**Comment by Kushagra42** [comment]
Status Update

Improved on socket and client code to allow easy functioning and integration with the main script.
Client-https://github.com/cu-ecen-5013/final-project-Kushagra42/blob/master/Socket_Client/Client.c 
 (aaeaa79fb8f3a6fa06acfcd6d6da154248f113e9)
Server-https://github.com/cu-ecen-5013/final-project-Kushagra42/blob/master/Socket_Server/Server.c
(cdf28be631b43de5fb94e110000c8c263325818e)

**Comment by Kushagra42** [comment]
Status Update: SPI Blocker: Since I was not able to load the SPI module successfully I have decided to move to an I2C based sensor after consulting with professor. Here I am attaching the link for the work that I had done working on SPI (Although I will not be using this content).

SPI application code: https://github.com/cu-ecen-5013/final-project-Kushagra42/blob/master/SPI_TEMP/spi_test.c 
(43c6dd57af5f28a413c4a56afad9b0a0c261b770)

SPI0 patch : https://github.com/cu-ecen-5013/final-project-Kushagra42/blob/master/SPI_TEMP/spi1_s0.patch

**Comment by Kushagra42** [comment]
Status: Closing this issue as I am moving to I2C based sensor for which I have created a new issue.
